kind: pipeline
type: docker
name: default

pipeline:
  build:
    image: node:latest
    commands:
      - npm install
      - npm run build
  docker:
    image: plugins/docker
    settings:
      repo: docker.grug.dev/portfolio
      registry: docker.grug.dev
      username: docker_username
      password: docker_password
      tags: [ latest ]