---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: node:latest
  commands:
  - npm install
  - npm run build

- name: docker
  pull: if-not-exists
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: docker.grug.dev
    repo: docker.grug.dev/portfolio
    tags: latest
  when:
    branch:
    - master

- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id: discord_webhook_id
    webhook_token: discord_webhook_token